Trying to get the secrets to work#A33

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -15,18 +15,18 @@ jobs:
         uses: actions/checkout@v2
       - name: check_repository_cleanliness
         run: |
-          UNWANTED_FILES=0
-          FOLE="de"
-          NB_FILES=0
-          FILE_INDEX=0
+          # UNWANTED_FILES=0
+          # FOLE="de"
+          # NB_FILES=0
+          # FILE_INDEX=0
           # echo "(1) NB_FILES = $NB_FILES"
           # for FILE in *
           #   let "NB_FILES = $NB_FILES+1"
           # echo "(2) NB_FILES = $NB_FILES"
           for FILE in *
           do
-            let "FILE_INDEX = $FILE_INDEX+1"
-            echo "UNWANTED_FILES = $UNWANTED_FILES"
+            # let "FILE_INDEX = $FILE_INDEX+1"
+            # echo "UNWANTED_FILES = $UNWANTED_FILES"
             if grep -q "*~" $FILE
             then
               echo "::error file=$FILE,line=1,endLine=0,title=Unwanted file detected::$FILE"
@@ -93,25 +93,54 @@ jobs:
               UNWANTED_FILES=1
             fi
 
-            if [ $UNWANTED_FILES -eq 1 ] && [ $FILE_INDEX -eq $NB_FILES ]
-            then
-              echo "::sucess file=$FOLE,line=1,endLine=0,title=Unwanted file sjdksdksjdkdetected::$FOLE"
-              # echo "::error file=$UNWANTED_FILES, line=1,endLine=0,title=Check if the repository is clean and void of any unwanted files (temp files, binary files, etc.)::Process completed with exit code 1"
-              echo "In UNWANTED_FILES"
-              # exit 1
-            fi
-            echo "UNWANTED_FILES= $UNWANTED_FILES"
-            FOLE=$FILE
-            echo "FOLE = $FOLE"
+            # if [ $UNWANTED_FILES -eq 1 ] && [ $FILE_INDEX -eq $NB_FILES ]
+            # then
+            #   echo "::sucess file=$FOLE,line=1,endLine=0,title=Unwanted file sjdksdksjdkdetected::$FOLE"
+            #   # echo "::error file=$UNWANTED_FILES, line=1,endLine=0,title=Check if the repository is clean and void of any unwanted files (temp files, binary files, etc.)::Process completed with exit code 1"
+            #   echo "In UNWANTED_FILES"
+            #   # exit 1
+            # fi
+            # echo "UNWANTED_FILES= $UNWANTED_FILES"
+            # FOLE=$FILE
+            # echo "FOLE = $FOLE"
           done
-          FILE='Test'
-          if [ $UNWANTED_FILES -eq 1 ]
-          then
-            echo "::sucess file=$FOLE,line=1,endLine=0,title=Unwanted file sjdksdksjdkdetected::$FOLE"
-            # echo "::error file=$UNWANTED_FILES, line=1,endLine=0,title=Check if the repository is clean and void of any unwanted files (temp files, binary files, etc.)::Process completed with exit code 1"
-            echo "In UNWANTED_FILES"
-            # exit 1
-          fi
+          # FILE='Test'
+          # if [ $UNWANTED_FILES -eq 1 ]
+          # then
+          #   echo "::sucess file=$FOLE,line=1,endLine=0,title=Unwanted file sjdksdksjdkdetected::$FOLE"
+          #   # echo "::error file=$UNWANTED_FILES, line=1,endLine=0,title=Check if the repository is clean and void of any unwanted files (temp files, binary files, etc.)::Process completed with exit code 1"
+          #   echo "In UNWANTED_FILES"
+          #   # exit 1
+          # fi
+
+to_gitlab:
+  runs-on: ubuntu-latest
+  steps:
+    - uses: actions/checkout@v2
+      with:
+    fetch-depth: 0
+    - uses: pixta-dev/repository-mirroring-action@v1
+      with:
+      target_repo_url:
+      https://github.com/HenraL/probable-system-chocolatine.git
+      ssh_private_key:
+      git@github.com:HenraL/probable-system-chocolatine.git
+
+to_codecommit:
+  runs-on: ubuntu-latest
+  steps:
+    - uses: actions/checkout@v2
+      with:
+      fetch-depth: 0
+    - uses: pixta-dev/repository-mirroring-action@v1
+      name: push_to_mirror
+      with:
+        target_repo_url:
+        https://github.com/HenraL/probable-system-chocolatine.git
+        ssh_private_key:
+        git@github.com:HenraL/probable-system-chocolatine.git
+        ssh_username:
+        ${{ secrets.SECRET_KEY }}
 
 
 # name: chocolatine
