working on the syntax#A29

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -16,8 +16,13 @@ jobs:
         run: |
           UNWANTED_FILES=0
           FOLE="de"
+          NB_FILES=0
+          FILE_INDEX=0
+          for FILE in *
+            let "NB_FILES= $NB_FILES+1"
           for FILE in *
           do
+            let "FILE_INDEX = $FILE_INDEX+1"
             echo "UNWANTED_FILES = $UNWANTED_FILES"
             if grep -q "*~" $FILE
             then
@@ -113,6 +118,13 @@ jobs:
             then
               echo "::error file=$FILE,line=1,endLine=0,title=Unwanted file detected::$FILE"
               UNWANTED_FILES=1
+            fi
+            if [ $UNWANTED_FILES -eq 1 ] && [ $FILE_INDEX -eq $NB_FILES ]
+            then
+              echo "::sucess file=$FOLE,line=1,endLine=0,title=Unwanted file sjdksdksjdkdetected::$FOLE"
+              # echo "::error file=$UNWANTED_FILES, line=1,endLine=0,title=Check if the repository is clean and void of any unwanted files (temp files, binary files, etc.)::Process completed with exit code 1"
+              echo "In UNWANTED_FILES"
+              # exit 1
             fi
             echo "UNWANTED_FILES= $UNWANTED_FILES"
             FOLE=$FILE
